
package org.tempuri;

import javax.xml.ws.WebFault;
import org.datacontract.schemas._2004._07.system.FaultException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FaultException", targetNamespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel")
public class IUtilitiesServicesConvertirTasaAnualAMensualFaultExceptionFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IUtilitiesServicesConvertirTasaAnualAMensualFaultExceptionFaultFaultMessage(String message, FaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IUtilitiesServicesConvertirTasaAnualAMensualFaultExceptionFaultFaultMessage(String message, FaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.datacontract.schemas._2004._07.system.FaultException
     */
    public FaultException getFaultInfo() {
        return faultInfo;
    }

}
