<#assign
scriptG = getterUtil.getString(themeDisplay.getThemeSetting("script-g"))
footerArticleIdSuper = getterUtil.getString(themeDisplay.getThemeSetting("footer-article-id-super"))
linkGovNal = getterUtil.getString(themeDisplay.getThemeSetting("link-gov-nacional"))
linkMarcaCol = getterUtil.getString(themeDisplay.getThemeSetting("url-marca-col"))
urlLogin = getterUtil.getString(themeDisplay.getThemeSetting("url-login"))
urlHome = getterUtil.getString(themeDisplay.getThemeSetting("url-home"))
urlImageGobierno = getterUtil.getString(themeDisplay.getThemeSetting("image-gobierno"))
urlImageLogo = getterUtil.getString(themeDisplay.getThemeSetting("image-logo"))
urlImageContast = getterUtil.getString(themeDisplay.getThemeSetting("image-contraste"))
urlImageTextDown = getterUtil.getString(themeDisplay.getThemeSetting("image-text-down"))
urlImageTextUp = getterUtil.getString(themeDisplay.getThemeSetting("image-text-up"))
urlImageRelief = getterUtil.getString(themeDisplay.getThemeSetting("image-relief"))
urlRelief = getterUtil.getString(themeDisplay.getThemeSetting("url-centro-relevo"))
urlImageConvertic = getterUtil.getString(themeDisplay.getThemeSetting("image-convertic"))
urlConvertic = getterUtil.getString(themeDisplay.getThemeSetting("url-convertic"))
urlImageChat = getterUtil.getString(themeDisplay.getThemeSetting("image-chat"))
urlImageMarcaPais = getterUtil.getString(themeDisplay.getThemeSetting("image-marca-pais"))
urlLanguage = getterUtil.getString(themeDisplay.getThemeSetting("url-idioma"))

urlSolveCase = getterUtil.getString(themeDisplay.getThemeSetting("url-resuelva-sucaso"))
urlParticipation = getterUtil.getString(themeDisplay.getThemeSetting("url-participación"))
urlComplaints = getterUtil.getString(themeDisplay.getThemeSetting("url-denuncias"))
urlPqrsd = getterUtil.getString(themeDisplay.getThemeSetting("url-pqrsd"))
urlAttentionChat = getterUtil.getString(themeDisplay.getThemeSetting("url-chat de atención"))
/>
