
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUtilitiesServices", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IUtilitiesServices {


    /**
     * 
     * @param numero
     * @param mayusculas
     * @return
     *     returns java.lang.String
     * @throws IUtilitiesServicesNumerosALetrasFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "NumerosALetras", action = "http://tempuri.org/IUtilitiesServices/NumerosALetras")
    @WebResult(name = "NumerosALetrasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NumerosALetras", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NumerosALetras")
    @ResponseWrapper(localName = "NumerosALetrasResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.NumerosALetrasResponse")
    public String numerosALetras(
        @WebParam(name = "numero", targetNamespace = "http://tempuri.org/")
        String numero,
        @WebParam(name = "mayusculas", targetNamespace = "http://tempuri.org/")
        Boolean mayusculas)
        throws IUtilitiesServicesNumerosALetrasFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param tasaAnual
     * @return
     *     returns java.lang.Float
     * @throws IUtilitiesServicesConvertirTasaAnualAMensualFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ConvertirTasaAnualAMensual", action = "http://tempuri.org/IUtilitiesServices/ConvertirTasaAnualAMensual")
    @WebResult(name = "ConvertirTasaAnualAMensualResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConvertirTasaAnualAMensual", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirTasaAnualAMensual")
    @ResponseWrapper(localName = "ConvertirTasaAnualAMensualResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirTasaAnualAMensualResponse")
    public Float convertirTasaAnualAMensual(
        @WebParam(name = "TasaAnual", targetNamespace = "http://tempuri.org/")
        String tasaAnual)
        throws IUtilitiesServicesConvertirTasaAnualAMensualFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param tasaAnual
     * @return
     *     returns java.lang.Float
     * @throws IUtilitiesServicesConvertirTasaAnualADiariaFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ConvertirTasaAnualADiaria", action = "http://tempuri.org/IUtilitiesServices/ConvertirTasaAnualADiaria")
    @WebResult(name = "ConvertirTasaAnualADiariaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConvertirTasaAnualADiaria", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirTasaAnualADiaria")
    @ResponseWrapper(localName = "ConvertirTasaAnualADiariaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirTasaAnualADiariaResponse")
    public Float convertirTasaAnualADiaria(
        @WebParam(name = "TasaAnual", targetNamespace = "http://tempuri.org/")
        String tasaAnual)
        throws IUtilitiesServicesConvertirTasaAnualADiariaFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param tasaMensual
     * @return
     *     returns java.lang.Float
     * @throws IUtilitiesServicesConvertirTasaMensualAAnualFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ConvertirTasaMensualAAnual", action = "http://tempuri.org/IUtilitiesServices/ConvertirTasaMensualAAnual")
    @WebResult(name = "ConvertirTasaMensualAAnualResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConvertirTasaMensualAAnual", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirTasaMensualAAnual")
    @ResponseWrapper(localName = "ConvertirTasaMensualAAnualResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirTasaMensualAAnualResponse")
    public Float convertirTasaMensualAAnual(
        @WebParam(name = "TasaMensual", targetNamespace = "http://tempuri.org/")
        String tasaMensual)
        throws IUtilitiesServicesConvertirTasaMensualAAnualFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param tasaMensual
     * @return
     *     returns java.lang.Float
     * @throws IUtilitiesServicesConvertirTasaMensualADiariaFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ConvertirTasaMensualADiaria", action = "http://tempuri.org/IUtilitiesServices/ConvertirTasaMensualADiaria")
    @WebResult(name = "ConvertirTasaMensualADiariaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConvertirTasaMensualADiaria", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirTasaMensualADiaria")
    @ResponseWrapper(localName = "ConvertirTasaMensualADiariaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirTasaMensualADiariaResponse")
    public Float convertirTasaMensualADiaria(
        @WebParam(name = "TasaMensual", targetNamespace = "http://tempuri.org/")
        String tasaMensual)
        throws IUtilitiesServicesConvertirTasaMensualADiariaFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param fecha
     * @return
     *     returns java.lang.String
     * @throws IUtilitiesServicesFechaFormato1FaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "FechaFormato1", action = "http://tempuri.org/IUtilitiesServices/FechaFormato1")
    @WebResult(name = "FechaFormato1Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FechaFormato1", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FechaFormato1")
    @ResponseWrapper(localName = "FechaFormato1Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FechaFormato1Response")
    public String fechaFormato1(
        @WebParam(name = "Fecha", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fecha)
        throws IUtilitiesServicesFechaFormato1FaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param fecha
     * @return
     *     returns java.lang.String
     * @throws IUtilitiesServicesFechaFormato2FaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "FechaFormato2", action = "http://tempuri.org/IUtilitiesServices/FechaFormato2")
    @WebResult(name = "FechaFormato2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FechaFormato2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FechaFormato2")
    @ResponseWrapper(localName = "FechaFormato2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FechaFormato2Response")
    public String fechaFormato2(
        @WebParam(name = "Fecha", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar fecha)
        throws IUtilitiesServicesFechaFormato2FaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param decifrar
     * @param cadena
     * @param urlEncode
     * @return
     *     returns java.lang.String
     * @throws IUtilitiesServicesCifradoFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "Cifrado", action = "http://tempuri.org/IUtilitiesServices/Cifrado")
    @WebResult(name = "CifradoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Cifrado", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Cifrado")
    @ResponseWrapper(localName = "CifradoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CifradoResponse")
    public String cifrado(
        @WebParam(name = "cadena", targetNamespace = "http://tempuri.org/")
        String cadena,
        @WebParam(name = "decifrar", targetNamespace = "http://tempuri.org/")
        Boolean decifrar,
        @WebParam(name = "urlEncode", targetNamespace = "http://tempuri.org/")
        Boolean urlEncode)
        throws IUtilitiesServicesCifradoFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param nit
     * @return
     *     returns java.lang.Integer
     * @throws IUtilitiesServicesCalcularDigitoVerificacionFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "CalcularDigitoVerificacion", action = "http://tempuri.org/IUtilitiesServices/CalcularDigitoVerificacion")
    @WebResult(name = "CalcularDigitoVerificacionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcularDigitoVerificacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcularDigitoVerificacion")
    @ResponseWrapper(localName = "CalcularDigitoVerificacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CalcularDigitoVerificacionResponse")
    public Integer calcularDigitoVerificacion(
        @WebParam(name = "Nit", targetNamespace = "http://tempuri.org/")
        String nit)
        throws IUtilitiesServicesCalcularDigitoVerificacionFaultExceptionFaultFaultMessage
    ;

    /**
     * 
     * @param documentoWord
     * @param extensionWord
     * @return
     *     returns byte[]
     * @throws IUtilitiesServicesConvertirPdfFaultExceptionFaultFaultMessage
     */
    @WebMethod(operationName = "ConvertirPdf", action = "http://tempuri.org/IUtilitiesServices/ConvertirPdf")
    @WebResult(name = "ConvertirPdfResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConvertirPdf", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirPdf")
    @ResponseWrapper(localName = "ConvertirPdfResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertirPdfResponse")
    public byte[] convertirPdf(
        @WebParam(name = "documentoWord", targetNamespace = "http://tempuri.org/")
        byte[] documentoWord,
        @WebParam(name = "extensionWord", targetNamespace = "http://tempuri.org/")
        String extensionWord)
        throws IUtilitiesServicesConvertirPdfFaultExceptionFaultFaultMessage
    ;

}
